# This is a template - DO NOT commit actual secrets to git!
# Use kubectl create secret or a secrets management tool
apiVersion: v1
kind: Secret
metadata:
  name: audience-manager-secrets
type: Opaque
stringData:
  database-url: "postgresql://admin:secretpassword@postgres:5432/audience_manager"
  postgres-user: "admin"
  postgres-password: "secretpassword"
  jwt-secret: "your-jwt-secret-here"
  api-key: "your-api-key-here"