# Cloud Build configuration for automated deployments
steps:
  # Install dependencies
  - name: 'python:3.11-slim'
    entrypoint: pip
    args: ['install', '-r', 'gcp/requirements.txt', '-t', '.']

  # Run tests
  - name: 'python:3.11-slim'
    entrypoint: python
    args: ['-m', 'pytest', 'src/api/tests/', '-v']
    env:
      - 'PYTHONPATH=/workspace/src'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'gcp/app.yaml', '--quiet']

  # Deploy cron jobs (if any)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['app', 'deploy', 'gcp/cron.yaml', '--quiet']

# Set timeout for the build
timeout: '1200s'

# Build options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'