FROM python:3.11-slim

WORKDIR /app

# Copy requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY . /app/gcp/
COPY ../src /app/src/

# Set Python path
ENV PYTHONPATH=/app

# Run the application
CMD exec gunicorn --bind :$PORT --workers 1 --threads 8 --timeout 0 gcp.main:app